Update KNMI methodology
ArtesiaWater/hydropandas pull request #202
Opened 2024-03-27 11:08 UTC by martinvonk

2024-03-28 13:04 UTC, OnnoEbbens commented
Thanks for this PR, this should speed up the 'fill_missing_measurements' a lot.

2024-03-29 15:57 UTC, OnnoEbbens requested changes

2024-03-29 15:57 UTC, OnnoEbbens commented on tests/test_001_to_from.py
> +        stn=310, meteo_var="PG", interval="hourly", start="2022-1-1", end="2023-1-1"
I am curious why you use 'PG' instead of 'P'. In the list of meteo_vars both options are available, see the docstring of the `hydropandas.read_knmi` function. In the updated json files I don't see 'P' listed anymore. Does this mean that not all meteo_vars are available in the json files and thus cannot be used anymore?

2024-03-29 15:57 UTC, OnnoEbbens commented on tests/test_001_to_from.py
> +        stn=310, meteo_var="PG", interval="hourly", start="2022-1-1", end="2023-1-1"
I think this also raises an error because PG is a 24 hour average and therefore not available at an hourly interval.

2024-03-29 15:57 UTC, OnnoEbbens commented on hydropandas/io/knmi.py
missing `adjust_time` in docstring.

2024-04-02 08:53 UTC, OnnoEbbens requested changes
Can you add and fix some of the docstrings? Then this PR is ready to be merged

2024-04-02 08:53 UTC, OnnoEbbens commented on hydropandas/io/knmi.py
> +def get_knmi_api(url: str, params: Dict[str, str]) -> StringIO:
missing docstring

2024-04-02 09:28 UTC, OnnoEbbens commented
Oh oh I celebrated to early. There is still an error in the knmi notebook.

2024-04-02 10:01 UTC, martinvonk commented on tests/test_001_to_from.py
> +        stn=310, meteo_var="PG", interval="hourly", start="2022-1-1", end="2023-1-1"
mistake on my part, didn't notice the hourly interval.

2024-04-02 10:01 UTC, martinvonk commented on hydropandas/io/knmi.py
added

2024-04-02 10:01 UTC, martinvonk commented on hydropandas/io/knmi.py
> +def get_knmi_api(url: str, params: Dict[str, str]) -> StringIO:
added the docstring

2024-04-02 15:02 UTC, OnnoEbbens requested changes
I think we should keep the behavior to return an empty dataframe when there is no data (instead of raising a pretty vague error). Is that doable?

2024-04-02 15:57 UTC, martinvonk commented
I'll have a look at the different kind's of exceptions raised when downloading KNMI data.

2024-04-03 10:37 UTC, OnnoEbbens approved these changes

2024-04-04 08:57 UTC, merged